In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
from sklearn.pipeline import Pipeline 
dataset = pd.read_csv('../data/ai4i2020.csv')
features_to_keep = ['Type','Air temperature [K]','Process temperature [K]','Rotational speed [rpm]','Torque [Nm]','Tool wear [min]']
X = dataset[features_to_keep]
y = dataset['Machine failure'].values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"), ["Type"])],
    remainder="passthrough"
)
X = ct.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=1)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
print("Train Accuracy:", model.score(X_train, y_train))
print("Test Accuracy:", model.score(X_test, y_test))
print(model.coef_)
print(model.intercept_)
import dice_ml
from dice_ml.utils import helpers
features_to_keep = ['Type', 'Air temperature [K]', 
                    'Process temperature [K]', 'Rotational speed [rpm]',
                     'Torque [Nm]', 'Tool wear [min]']
df_dice = dataset[features_to_keep + ['Machine failure']]
data_dice = dice_ml.Data(
    dataframe=df_dice,
    continuous_features=['Air temperature [K]',
                          'Process temperature [K]', 'Rotational speed [rpm]',
                          'Torque [Nm]', 'Tool wear [min]'],
    categorical_features=['Type'],
    outcome_name='Machine failure'
)

target_model = Pipeline(steps=[
    ('preprocessor', ct),
    ('classifier', model)
])

model_di = dice_ml.Model(model=target_model, backend='sklearn')
explainer = dice_ml.Dice(data_dice, model_di, method='genetic')
feature_names = ['Product ID', 
    'Type', 
    'Air temperature [K]', 
    'Process temperature [K]', 
    'Rotational speed [rpm]', 
    'Torque [Nm]', 
    'Tool wear [min]']
input_datapoint = dataset.loc[[0], features_to_keep]   
features_to_vary=['Air temperature [K]','Process temperature [K]','Tool wear [min]',
                  'Torque [Nm]','Rotational speed [rpm]']
permitted_range = {f: [dataset[f].min(), dataset[f].max()] for f in features_to_vary}

print ( "gentic counterfactual  method explantion")
print ("<------------------------>")
counterfactuals = explainer.generate_counterfactuals(
    input_datapoint,
    total_CFs=2,
    desired_class="opposite",
    features_to_vary=features_to_vary,
    permitted_range=permitted_range
)
counterfactuals.visualize_as_dataframe(show_only_changes=False)


def explain_cf(original, cf):
    changes = []
    for col in original.index:
        if original[col] != cf[col]:
            changes.append(f"{col}: {original[col]} → {cf[col]}")
    return changes

for i, row in counterfactuals.cf_examples_list[0].final_cfs_df.iterrows():
    print("CF", i+1)
    changes = explain_cf(input_datapoint.iloc[0], row)
    for c in changes:
        print("-", c)

def explain_cf_changes(original_row, cf_row):
    recommendations = []

    for col in original_row.index:
        old = original_row[col]
        new = cf_row[col]

        if old != new:
            if new > old:
                recommendations.append(f"Increase {col} from {old} to {new}")
            else:
                recommendations.append(f"Decrease {col} from {old} to {new}")

    return recommendations
original_row = input_datapoint.iloc[0]

cf_df = counterfactuals.cf_examples_list[0].final_cfs_df

for i, row in cf_df.iterrows():
    print(f"\nCounterfactual {i+1}:")
    recs = explain_cf_changes(original_row, row)
    for r in recs:
        print("-", r)

print("------------------------ start of random method explanation ------------------------")                
print ( "random counterfactual method explntion")
print("<-------------------->")
explainer2 = dice_ml.Dice(data_dice, model_di, method='random')
counterfactuals = explainer2.generate_counterfactuals(
         input_datapoint, 
         total_CFs=2, 
        desired_class='opposite',
        features_to_vary=features_to_vary,
         permitted_range= permitted_range
            ,sample_size=10000)
counterfactuals.visualize_as_dataframe(show_only_changes=False)

def explain_cf(original, cf):
    changes = []
    for col in original.index:
        if original[col] != cf[col]:
            changes.append(f"{col}: {original[col]} → {cf[col]}")
    return changes

for i, row in counterfactuals.cf_examples_list[0].final_cfs_df.iterrows():
    print("CF", i+1)
    changes = explain_cf(input_datapoint.iloc[0], row)
    for c in changes:
        print("-", c)

def explain_cf_changes(original_row, cf_row):
    recommendations = []

    for col in original_row.index:
        old = original_row[col]
        new = cf_row[col]

        if old != new:
            if new > old:
                recommendations.append(f"Increase {col} from {old} to {new}")
            else:
                recommendations.append(f"Decrease {col} from {old} to {new}")

    return recommendations
original_row = input_datapoint.iloc[0]

cf_df = counterfactuals.cf_examples_list[0].final_cfs_df

for i, row in cf_df.iterrows():
    print(f"\nCounterfactual {i+1}:")
    recs = explain_cf_changes(original_row, row)
    for r in recs:
        print("-", r)
        
print("------------------------ start of kdtree method explanation ------------------------")
print ( "kdtree counterfactual method explntion")
print("<-------------------->")
explainer3 = dice_ml.Dice(data_dice, model_di, method='kdtree')
counterfactuals = explainer3.generate_counterfactuals(
         input_datapoint, 
         total_CFs=2, 
        desired_class="opposite",
        features_to_vary=features_to_vary,
         permitted_range= permitted_range)
counterfactuals.visualize_as_dataframe(show_only_changes=False)

def explain_cf(original, cf):
    changes = []
    for col in original.index:
        if original[col] != cf[col]:
            changes.append(f"{col}: {original[col]} → {cf[col]}")
    return changes

for i, row in counterfactuals.cf_examples_list[0].final_cfs_df.iterrows():
    print("CF", i+1)
    changes = explain_cf(input_datapoint.iloc[0], row)
    for c in changes:
        print("-", c)
def explain_cf_changes(original_row, cf_row):
    recommendations = []

    for col in original_row.index:
        old = original_row[col]
        new = cf_row[col]

        if old != new:
            if new > old:
                recommendations.append(f"Increase {col} from {old} to {new}")
            else:
                recommendations.append(f"Decrease {col} from {old} to {new}")

    return recommendations
original_row = input_datapoint.iloc[0]

cf_df = counterfactuals.cf_examples_list[0].final_cfs_df

fcf_df = counterfactuals.cf_examples_list[0].final_cfs_df

original_row = input_datapoint.iloc[0]

cf_df = counterfactuals.cf_examples_list[0].final_cfs_df
for i, row in cf_df.iterrows():
    print(f"\nCounterfactual {i+1}:")
    recs = explain_cf_changes(original_row, row)
    for r in recs:
        print("-", r)

c:\Users\DELL\Desktop\bacholer\venv\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train Accuracy: 0.969375
Test Accuracy: 0.9735
[[ 0.36017881 -0.0138746   0.7916988  -0.87508908  0.0108625   0.26809426
   0.01255765]]
[-0.01066651]
gentic counterfactual  method explantion
<------------------------>

100%|██████████| 1/1 [00:03<00:00,  3.48s/it]

Query instance (original outcome : 0)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.100006,308.600006,1551,42.799999,0,0

Diverse Counterfactual set (new outcome: 1)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,301.9,308.6,1168,68.6,0,1

CF 1
- Air temperature [K]: 298.1 → 301.9
- Rotational speed [rpm]: 1551 → 1168
- Torque [Nm]: 42.8 → 68.6

Counterfactual 1:
- Increase Air temperature [K] from 298.1 to 301.9
- Decrease Rotational speed [rpm] from 1551 to 1168
- Increase Torque [Nm] from 42.8 to 68.6
------------------------ start of random method explanation ------------------------
random counterfactual method explntion
<-------------------->

100%|██████████| 1/1 [00:00<00:00,  1.36it/s]

Query instance (original outcome : 0)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.100006,308.600006,1551,42.799999,0,0

Diverse Counterfactual set (new outcome: 1)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.1,308.6,2550,42.8,55,1
1,M,298.1,308.6,2333,37.3,0,1

CF 1
- Rotational speed [rpm]: 1551 → 2550
- Tool wear [min]: 0 → 55
CF 2
- Rotational speed [rpm]: 1551 → 2333
- Torque [Nm]: 42.8 → 37.3

Counterfactual 1:
- Increase Rotational speed [rpm] from 1551 to 2550
- Increase Tool wear [min] from 0 to 55

Counterfactual 2:
- Increase Rotational speed [rpm] from 1551 to 2333
- Decrease Torque [Nm] from 42.8 to 37.3
------------------------ start of kdtree method explanation ------------------------
kdtree counterfactual method explntion
<-------------------->

100%|██████████| 1/1 [00:00<00:00, 10.13it/s]

Query instance (original outcome : 0)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.100006,308.600006,1551,42.799999,0,0

Diverse Counterfactual set (new outcome: 1)

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
4547,M,302.5,310.4,1451,53.6,194,1
4353,M,302.0,309.7,1386,62.7,142,1

CF 4548
- Air temperature [K]: 298.1 → 302.5
- Process temperature [K]: 308.6 → 310.4
- Rotational speed [rpm]: 1551 → 1451
- Torque [Nm]: 42.8 → 53.6
- Tool wear [min]: 0 → 194
CF 4354
- Air temperature [K]: 298.1 → 302.0
- Process temperature [K]: 308.6 → 309.7
- Rotational speed [rpm]: 1551 → 1386
- Torque [Nm]: 42.8 → 62.7
- Tool wear [min]: 0 → 142

Counterfactual 4548:
- Increase Air temperature [K] from 298.1 to 302.5
- Increase Process temperature [K] from 308.6 to 310.4
- Decrease Rotational speed [rpm] from 1551 to 1451
- Increase Torque [Nm] from 42.8 to 53.6
- Increase Tool wear [min] from 0 to 194

Counterfactual 4354:
- Increase Air temperature [K] from 298.1 to 302.0
- Increase Process temperature [K] from 308.6 to 309.7
- Decrease Rotational speed [rpm] from 1551 to 1386
- Increase Torque [Nm] from 42.8 to 62.7
- Increase Tool wear [min] from 0 to 142